### ISSUE TITLE
memory allocation of 2621440000 bytes failed

### ISSUE THREAD

**Issue by wds657** [a137x/plutus-rustus#1]
Hi thanks for programming this, i have error when read the 00.pickle (UPDATED) in one file, in plutus original no error.

![Captura de pantalla 2022-08-31 141758](https://user-images.githubusercontent.com/26626600/187740754-1e2f1ddc-f01e-43f1-8e0d-c18ee4488c6a.png)
![Captura de pantalla 2022-08-31 141329](https://user-images.githubusercontent.com/26626600/187740758-b4228b29-c8ca-4498-ad2d-cbc8c72e21f6.png)

**Comment by ethicalliving** [comment]
I don't know Rust but could this be because of lack of available ram? 

I have tested a137x's database with the code and it started to work without a problem. I tested it on Ubuntu 20.04 with 32GB ram.

**Comment by wds657** [comment]
i had original plutus running, i closed it and this fork worked ok
