### ISSUE TITLE
Rewrite 

### ISSUE THREAD

**Issue by ghost** [a137x/plutus-rustus#10]
Hello! I like this implementation of Plutus.
Currently, I'm doing a full rewrite of the tool, will add a new way of simple database convertation, refactor and optimise the code.
Will do a PR soon.

**Comment by a137x** [comment]
Hello.
PR are welcome, thank you.

**Comment by sa6ta6ni6c** [comment]
pr sent

**Comment by a137x** [comment]
thanks for your contribution
