### ISSUE TITLE
Thank you 

### ISSUE THREAD

**Issue by ghost** [a137x/plutus-rustus#12]
Thank you for the advices on refactoring.
I guess we all learn something new all the time 😀

I’m currently trying to optimise the code further, using rayon library instead of Tokio.
Yesterday, I was able to increase iter/sec to 40k!!!

I’m also trying to implement some functions in Assembly, but currently no luck.

**Comment by ghost** [comment]
Also, script uses pickled db for addresses, is there any point in using other possible methods like sql? I guess it could improve performance. Lastly, pickle is mostly used for python, in rust it may be not as effective

**Comment by a137x** [comment]
> Also, script uses pickled db for addresses, is there any point in using other possible methods like sql? I guess it could improve performance. Lastly, pickle is mostly used for python, in rust it may be not as effective

Database type files does not affect performance of the program as database loaded only once and then all data read from in-memory HashMap.
