### ISSUE TITLE
Compile on Mac?

### ISSUE THREAD

**Issue by bane77111** [a137x/plutus-rustus#3]
Can you guys please tell me how to compile this on Mac? 

Thanks!

**Comment by samgray96** [comment]
Hi Bane,

I just installed rust with curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

and then compiled with the command in the readme which is cargo rustc --release -- -C target-cpu=native

seems to be running good for me on my 2019 MBP

**Comment by bane77111** [comment]
> Hi Bane,
> 
> I just installed rust with curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> 
> and then compiled with the command in the readme which is cargo rustc --release -- -C target-cpu=native
> 
> seems to be running good for me on my 2019 MBP

Thanks for your help, now its working!
