### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by lexick2016** [a137x/plutus-rustus#5]
Hi guys,

Please help out if you can.
Once you get an address, private key, hex private key in Wallet Import Format, and P2PKH wallet address how exactly I can access that wallet, I don't even know what wallet was used.
My simple questions is what should I do with the info, where to use it to access the BTC :(
Thanks

**Comment by a137x** [comment]
Sorry for a bit of delay in response. 
First of all, If you found  any "btc address & private key" pair using this program, consider yourself as luckiest person on this planet.
Regarding your question:
Please read [this](https://bitcoin.stackexchange.com/questions/61347/how-to-restore-my-old-wallet-from-address-and-privatekey)

Regards,
